name: Howlers
author: supersimple33
description: This plugin sets wolves to howl at the moon
version: 0.1

api-version: 1.17
main: com.github.supersimple33.howlers.Woof

permissions:
  howlers.reload:
    description: Allows executor 
    default: op
  

commands:
  hwreload:
    description: This reloads the config of the howlers plugin
    permission: howlers.reload
    permission-message: You do not have /<permission>
    usage: /<command>
